apiVersion: v1
kind: Service
metadata:
  labels:
    app: toil-wes
  name: toil
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: toil-wes
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
