apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: 4369-tcp
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: 5671-tcp
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: 5672-tcp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: 15691-tcp
    port: 15691
    protocol: TCP
    targetPort: 15691
  - name: 15692-tcp
    port: 15692
    protocol: TCP
    targetPort: 15692
  - name: 25672-tcp
    port: 25672
    protocol: TCP
    targetPort: 25672
  selector:
    deploymentconfig: rabbitmq
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
